<a href="https://colab.research.google.com/github/chohj118/kagglestudy/blob/main/tensorflow_beginner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

TensorFlow 설정하기

In [1]:
import tensorflow as tf
print('TensorFlow version:', tf.__version__)

TensorFlow version: 2.9.2


데이터세트 로드하기

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


머신 러닝 모델 빌드하기

In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[0.05866791, 0.10393719, 0.0852942 , 0.1135688 , 0.07337178,
        0.05098926, 0.16672961, 0.18546835, 0.05264218, 0.10933071]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.09585742, 0.10029653, 0.09844404, 0.10126722, 0.09727731,
        0.09512419, 0.10679633, 0.10881643, 0.09528154, 0.10083895]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

2.352572

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5


/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


1875/1875 [==============================] - 5s 3ms/step - loss: 0.2919 - accuracy: 0.9149
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1388 - accuracy: 0.9593
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1065 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0867 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0743 - accuracy: 0.9768


In [11]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0645 - accuracy: 0.9794
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0562 - accuracy: 0.9822
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0532 - accuracy: 0.9825
Epoch 4/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0462 - accuracy: 0.9850
Epoch 5/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0432 - accuracy: 0.9855
313/313 - 1s - loss: 0.0728 - accuracy: 0.9808 - 575ms/epoch - 2ms/step


[0.0728246346116066, 0.9807999730110168]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533676, 0.08533676, 0.08533676, 0.08533683, 0.08533676,
        0.08533676, 0.08533676, 0.2319691 , 0.08533676, 0.08533677],
       [0.08533674, 0.08533677, 0.23196927, 0.08533674, 0.08533674,
        0.08533674, 0.08533674, 0.08533674, 0.08533674, 0.08533674],
       [0.08534028, 0.2319137 , 0.08534259, 0.08534028, 0.08534068,
        0.08534027, 0.08534028, 0.08536053, 0.0853412 , 0.08534026],
       [0.23196901, 0.08533677, 0.08533688, 0.08533677, 0.08533677,
        0.08533677, 0.08533677, 0.08533677, 0.08533677, 0.08533677],
       [0.08533969, 0.08533967, 0.08533967, 0.08533967, 0.23192278,
        0.08533967, 0.08533967, 0.08533973, 0.08533967, 0.08535966]],
      dtype=float32)>